
services:
  db:
    image: postgres:15.6
    restart: always
    command: -c 'max_connections=1000'
    environment:
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_INITDB_ARGS: --auth=md5
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: unprice
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # pgbouncer:
  #   image: edoburu/pgbouncer
  #   environment:
  #     DB_USER: postgres
  #     DB_PASSWORD: postgres
  #     DB_HOST: db
  #     DB_NAME: postgres
  #     POOL_MODE: session
  #     ADMIN_USERS: postgres
  #   ports:
  #     - "5432:5432"
  #   depends_on:
  #     - db

  pg_proxy:
    platform: linux/x86_64
    image: ghcr.io/neondatabase/wsproxy:latest
    environment:
      # APPEND_PORT: "pgbouncer:5432"
      # APPEND_PORT: "db:5432"
      ALLOW_ADDR_REGEX: ".*"
      LOG_TRAFFIC: "true"
      # USE_HOST_HEADER: "false"
    ports:
      - "5433:80"
    depends_on:
      # - pgbouncer
      - db

  # tinybird:
  #   platform: linux/amd64
  #   image: tinybirdco/tinybird-local:latest
  #   ports:
  #     - "7181:7181"
  #     - "8080:80"

  # redis:
  #   image: redis
  #   ports:
  #     - "6379:6379"

  # serverless-redis-http:
  #   ports:
  #     - "8079:80"
  #   image: hiett/serverless-redis-http:latest
  #   environment:
  #     SRH_MODE: env
  #     SRH_TOKEN: example_token
  #     SRH_CONNECTION_STRING: "redis://redis:6379" # Using `redis` hostname since they're in the same Docker network.

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: always
    volumes:
      - ./mailpit:/data
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP server
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  pgdata:
