version: "3.9"

services:
  db:
    image: postgres:15.6
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_INITDB_ARGS: --auth=md5
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgbouncer:
    image: edoburu/pgbouncer
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_NAME: postgres
      POOL_MODE: session
      ADMIN_USERS: postgres
    ports:
      - "5432:5432"
    depends_on:
      - db

  pg_proxy:
    platform: linux/x86_64
    image: ghcr.io/neondatabase/wsproxy:latest
    environment:
      APPEND_PORT: "pgbouncer:5432"
      ALLOW_ADDR_REGEX: ".*"
      LOG_TRAFFIC: "true"
    ports:
      - "5433:80"
    depends_on:
      - pgbouncer

volumes:
  pgdata:
